// increase dan decrease
#include <iostream.h>
#include <conio.h>
main()
{
	int i1=2,i2=2;
   int j1=5,j2=5;
   int a,b,c,d;
   a=++i1;
   b=i2++;
   c=--j1;
   d=j2--;
   cout<<"\nNilai a = "<<a;
   cout<<"\Nilai i1 =  "<<b;
   cout<<"\nNilai i2 = "<<i2;
   cout<<"\n\nNilai c ="<<c;
   cout<<"\nNilai j1 = "<<j1;
   cout<<"\n\nNilai d = "<<d;
   cout<<"\nNilai j2 = "<<j2;
   getch();
   }

